SSAFIT/FE

- PairFE/vue-pair-fe/src/api/relationship.js
- PairFE/vue-pair-fe/src/api/reply.js
- PairFE/vue-pair-fe/src/api/user.js
생성한 파일
1. reply.js 
2. user.js 
3. relationship.js
> [INIT] 프로젝트 구조 세팅

- PairFE/vue-pair-fe/src/api/post.js
- PairFE/vue-pair-fe/src/components/post/PostList.vue
- PairFE/vue-pair-fe/src/router/index.js
- PairFE/vue-pair-fe/src/views/MainView.vue
- PairFE/vue-pair-fe/src/views/post/PostView.vue
> [POST] PostList , PartList조회 기능 구현

- PairFE/vue-pair-fe/package-lock.json
- PairFE/vue-pair-fe/package.json
- PairFE/vue-pair-fe/src/api/post.js
- PairFE/vue-pair-fe/src/components/post/PostUpdate.vue
- PairFE/vue-pair-fe/src/main.js
- PairFE/vue-pair-fe/src/store/index.js
> [POST] POST UPDATE 기능 구현

- PairFE/vue-pair-fe/src/api/post.js
- PairFE/vue-pair-fe/src/components/post/PostCreate.vue
- PairFE/vue-pair-fe/src/components/post/PostList.vue
- PairFE/vue-pair-fe/src/store/index.js
> [POST] POST 등록 기능 & POST LIST 페이지네이션

- PairFE/vue-pair-fe/src/api/like.js
- PairFE/vue-pair-fe/src/components/post/PostList.vue
- PairFE/vue-pair-fe/src/store/index.js
> [LIKE] 좋아요 등록, 삭제 기능 구현

- PairFE/vue-pair-fe/src/components/post/RecommendAge.vue
- PairFE/vue-pair-fe/src/components/post/RecommendGender.vue
- PairFE/vue-pair-fe/src/views/MainView.vue
> [POST] 유저의 연령, 성별에 따라 좋아요 누른 영상 추천

- PairFE/vue-pair-fe/src/components/user/UserLogin.vue
- PairFE/vue-pair-fe/src/router/index.js
- PairFE/vue-pair-fe/src/store/index.js
> [REFACTOR] USER 로그인 기능 수정

- PairFE/vue-pair-fe/src/api/post.js
- PairFE/vue-pair-fe/src/components/post/PostLike.vue
- PairFE/vue-pair-fe/src/components/post/PostList.vue
- PairFE/vue-pair-fe/src/components/post/RecommendAge.vue
- PairFE/vue-pair-fe/src/components/post/RecommendGender.vue
- PairFE/vue-pair-fe/src/components/post/TopList.vue
- PairFE/vue-pair-fe/src/views/MainView.vue
> [POST] 유저가 좋아요 누른 영상 리스트 조회 기능 구현

- PairFE/vue-pair-fe/src/App.vue
- PairFE/vue-pair-fe/src/components/common/AppHeader.vue
- PairFE/vue-pair-fe/src/components/user/UserDetail.vue
- PairFE/vue-pair-fe/src/components/user/UserLogin.vue
- PairFE/vue-pair-fe/src/store/index.js
> [USER] 헤더(메인, 로그인, 로그아웃)/상세 조회/탈퇴/로그아웃 기능 구현

- PairFE/vue-pair-fe/src/components/map/HealthMap.vue
- PairFE/vue-pair-fe/src/components/post/TopList.vue
- PairFE/vue-pair-fe/src/views/MainView.vue
#31  카카오맵 지도 구현 및 로그인, 로그아웃 시 메인 화면 구성
> [MAP] 카카오맵 지도 구현 및 메인화면 구성

- PairFE/vue-pair-fe/src/components/user/UserFollow.vue
- PairFE/vue-pair-fe/src/store/index.js
- PairFE/vue-pair-fe/src/views/MainView.vue
> [RELATIONSHIP] 유저의 팔로워, 팔로잉 조회, 추가, 삭제 기능 구현

- PairFE/vue-pair-fe/src/views/MainView.vue
> refactor : MainView 코드 원 상태로 복구

- PairFE/vue-pair-fe/package-lock.json
- PairFE/vue-pair-fe/package.json
- PairFE/vue-pair-fe/src/api/user.js
- PairFE/vue-pair-fe/src/components/user/UserJoin.vue
- PairFE/vue-pair-fe/src/main.js
> [USER] 유저 삽입 기능 구현

- PairFE/vue-pair-fe/src/components/post/PostList.vue
- PairFE/vue-pair-fe/src/components/post/RecommendAge.vue
- PairFE/vue-pair-fe/src/components/post/RecommendGender.vue
- PairFE/vue-pair-fe/src/components/post/TopList.vue
- PairFE/vue-pair-fe/src/views/MainView.vue
#42 
PostList 영상 검색 파트 및 연령대, 성별 선택에 따른 메인 화면 구성 수정
> [POST] POSTLIST 영상 검색 파트 및 메인 화면 수정

- PairFE/vue-pair-fe/src/components/admin/PostManagement.vue
- PairFE/vue-pair-fe/src/router/index.js
- PairFE/vue-pair-fe/src/views/MainView.vue
- PairFE/vue-pair-fe/src/views/admin/AdminView.vue
> [POST] 관리자 영상 게시물 관리 기능 구현

- PairFE/vue-pair-fe/src/api/user.js
- PairFE/vue-pair-fe/src/components/admin/UserManagement.vue
- PairFE/vue-pair-fe/src/views/admin/AdminView.vue
> [USER] 관리자 회원 관리 기능 구현

- PairFE/vue-pair-fe/src/components/common/AppHeader.vue
- PairFE/vue-pair-fe/src/components/user/UserDetail.vue
- PairFE/vue-pair-fe/src/router/index.js
> [REFACTOR] 유저 상세 조회, 유저 경로 수정

- PairFE/vue-pair-fe/src/api/comment.js
- PairFE/vue-pair-fe/src/api/reply.js
- PairFE/vue-pair-fe/src/components/comment/CommentList.vue
- PairFE/vue-pair-fe/src/components/post/PostDetail.vue
> [COMMENT] 댓글/대댓글 기능구현

- PairFE/vue-pair-fe/src/components/user/UserDetail.vue
- PairFE/vue-pair-fe/src/components/user/UserLogin.vue
- PairFE/vue-pair-fe/src/components/user/UserUpdate.vue
- PairFE/vue-pair-fe/src/store/index.js
> [REFACTOR/USER] 유저 상세 조회 수정, 유저 경로 수정, 유저 수정 기능 구현

- PairFE/vue-pair-fe/src/components/common/AppHeader.vue
> [COMMON] header 완성
